### ISSUE TITLE
Redundant Code?

### ISSUE THREAD

**Issue by Kelukin** [wata-orz/vertex_cover#1]
I found some question in the code of VCSolver.java.
In VCSolver.java:443, the code is 
```java
                                ok = false;
				if (ok) {
					for (int j = 0; j < qt; j++) {
						v = que[j];
						if (v >= n) set(v - n, 0);
					}
				}
```
The variable `ok` is initialized with `true`, and the afterward code embedding in `if` won't be processed. Should the `ok = false;` be removed? Or the code between line 401-451 does not make sense?

**Comment by wata-orz** [comment]
The line "ok = false" should be deleted.
The code is to compute strongly connected component decomposition to expand the integral-part of the half-integral solution.
Perhaps I inserted "ok = false" to examine the effect of this optimization, and forgot to remove it.
I don't think this will affect the performance so much, but I will test again later.
